import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    language: 'Language',
    english: 'English',
    vietnamese: 'Tiếng Việt',
    nav: {
      home: 'Home',
      transactions: 'Transactions',
      categories: 'Categories',
      statistics: 'Statistics',
      settings: 'Settings',
    },
    header: {
      title: 'Expense manager',
      subtitle: 'Fast, clean and modern expense tracking for your business.',
    },
    home: {
      loading: 'Loading dashboard...',
      welcomeTitle: 'Welcome to Finance Studio',
      welcomeText: 'Track expenses, categorize spending, and explore your dashboard even before signing in.',
      gettingStarted: 'Getting started',
      step1: 'Add categories and manage your budget',
      step2: 'Log payments and income in seconds',
      step3: 'View performance charts and trends',
      overview: 'Dashboard overview',
      overviewTitle: 'Manage your money with clarity',
      overviewText: 'A modern expense tracker with quick insights, smart category control, and trend analytics for your finances.',
      wallet: 'Wallet',
      expenses: 'Expenses',
      walletBalance: 'Wallet Balance',
      latestInsights: 'Latest insights',
      latestInsightsText: 'A quick snapshot of your spending categories and cash flow.',
      topCategory: 'Top category',
      noCategories: 'No categories yet',
      transactionCount: 'Transaction count',
      expenseVsIncome: 'Expense vs Income',
      expenseByCategory: 'Expenses by Category',
      monthlyTrend: 'Monthly Trend',
      basedOn: 'Based on your recorded transactions',
      income: 'Income',
      expensesChart: 'Expenses',
      noData: 'No data',
    },
    transaction: {
      loading: 'Loading...',
      requiredLoginTitle: 'Login required',
      requiredLoginText: 'Please log in to manage your transactions.',
      title: 'Transactions',
      subtitle: 'Transaction Management',
      records: 'records found',
      addNew: 'Add New Transaction',
      description: 'Description',
      amount: 'Amount',
      chooseCategory: 'Choose category',
      note: 'Note (optional)',
      addButton: 'Add Transaction',
      viewDetails: 'View Details',
      hideDetails: 'Hide Details',
      delete: 'Delete',
      noteLabel: 'Note',
      noNote: 'No additional notes available.',
      completeFields: 'Please complete all transaction fields.',
      fallbackLocal: 'Transaction saved locally because Supabase is unavailable.',
      failedAdd: 'Failed to add transaction.',
      failedDelete: 'Failed to delete transaction.',
      confirmDelete: 'Are you sure you want to delete this transaction?',
      loadCategoriesError: 'Failed to load categories.',
      loadTransactionsError: 'Failed to load transactions.',
      unknown: 'Unknown',
      noCategories: 'No categories yet',
      date: 'Date',
    },
    categories: {
      title: 'Category Management',
      subtitle: 'Create, edit, and organize your income and expense categories.',
      loading: 'Loading categories...',
      addTitle: 'Add Category',
      nameLabel: 'Category Name',
      namePlaceholder: 'Enter category name',
      typeLabel: 'Category Type',
      expense: 'Expense',
      income: 'Income',
      addButton: 'Add Category',
      yourCategories: 'Your Categories',
      items: 'items',
      noCategories: 'No categories yet. Start by adding a category.',
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      delete: 'Delete',
      loginRequiredTitle: 'Login required',
      loginRequiredText: 'Please login to view and manage your categories.',
      supabaseNotConfigured: 'Supabase not configured',
      supabaseConfigText: 'Please add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to manage categories.',
      errorName: 'Please enter a category name',
      loginFirst: 'Please login first to add a category.',
      fallbackLocal: 'Category saved locally because Supabase is unavailable.',
      deleteLogin: 'Please login first.',
      emptyName: 'Category name cannot be empty!',
      updateError: 'Error updating category.',
      addError: 'Error adding category.',
      deleteError: 'Error deleting category.',
      loadError: 'Failed to load categories.',
      missingTable: 'The categories table was not found. Using local data instead.',
    },
    statistics: {
      loading: 'Loading statistics...',
      title: 'Statistics',
      subtitle: 'Track where your wallet is spent each month.',
      supabaseConfigText: 'Supabase is not configured. Please add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.',
      signInText: 'Sign in to view personalized expense analytics.',
      totalIncome: 'Total Income',
      totalExpenses: 'Total Expenses',
      balance: 'Balance',
      monthlyTitle: 'Monthly Spending Analysis',
      quarterlyTitle: 'Quarterly Income vs Expense',
      categoryTitle: 'Expense Breakdown by Category',
    },
    settings: {
      account: 'Account',
      title: 'Profile Settings',
      subtitle: 'Manage your account, preferences and wallet.',
      loading: 'Loading profile information...',
      pleaseLogin: 'Please log in',
      loginText: 'User information not found. Please log in again to continue.',
      goToLogin: 'Go to Login',
      supabaseNotConfigured: 'Supabase is not configured',
      supabaseConfigText: 'Please add environment variables VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to load profile information.',
      walletBalance: 'Wallet Balance',
      updatePhoto: 'Click the camera icon to update your profile photo.',
      personalInfo: 'Personal Information',
      personalInfoText: 'Update your basic profile information.',
      username: 'Username',
      emailAddress: 'Email Address',
      emailHint: 'Email address cannot be changed here.',
      currency: 'Currency',
      passwordSecurity: 'Password & Security',
      passwordSecurityText: 'Keep your account secure with a strong password.',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      passwordHint: 'Required only when changing your password.',
      newPasswordHint: 'Leave blank if you don\'t want to change it.',
      wallet: 'Wallet',
      walletText: 'Manage your current wallet balance.',
      currentWalletBalance: 'Current Wallet Balance',
      amount: 'Amount',
      action: 'Action',
      addAmount: 'Add Amount',
      setNewValue: 'Set New Value',
      addDesc: 'adds the entered amount to your current balance.',
      setDesc: 'replaces your current balance.',
      logout: 'Logout',
      saveChanges: 'Save Changes',
      saving: 'Saving...',
      usernamePlaceholder: 'Enter your username',
      emailPlaceholder: 'Enter email',
      amountPlaceholder: 'Enter amount, e.g. 1,000',
      accountMessage: 'User',
      enterCurrentPassword: 'Enter current password',
      enterNewPassword: 'Enter new password',
      usernameRequired: 'Username cannot be empty.',
      passwordRequired: 'Please enter your old password to update your new password.',
      oldPasswordIncorrect: 'Old password is incorrect.',
      invalidBalance: 'Please enter a valid non-negative balance amount.',
      saveSuccess: 'Settings saved successfully!',
      saveError: 'Failed to save settings. Please try again.',
      profileText: 'Manage your account, preferences and wallet.',
      currentBalanceLabel: 'Current Wallet Balance',
    },
    auth: {
      loginTitle: 'Wallet Login',
      loginSubtitle: 'Sign in to access your virtual wallet and expense reports.',
      email: 'Email',
      password: 'Password',
      emailPlaceholder: 'Email address',
      passwordPlaceholder: 'Password',
      signingIn: 'Signing In...',
      signIn: 'Sign In',
      noAccount: 'Don’t have an account?',
      signUp: 'Sign up',
      forgotPassword: 'Forgot password?',
      forgotPasswordTitle: 'Reset your password',
      forgotPasswordText: 'Enter your email and we will send you a password reset link.',
      sendResetLink: 'Send reset link',
      resetLinkSent: 'Please check your email for the password reset link.',
      resetLinkError: 'Unable to send the reset link. Please try again.',
      backToLogin: 'Back to login',
      resetPasswordTitle: 'Set a new password',
      newPassword: 'New password',
      confirmNewPassword: 'Confirm new password',
      passwordUpdated: 'Your password has been updated. You can now sign in.',
      passwordUpdateError: 'Unable to update your password. Please try again.',
      passwordsDoNotMatch: 'Passwords do not match.',
      invalidCredentials: 'Invalid email or password',
      confirmEmail: 'Please confirm your email or check your credentials.',
      genericError: 'An error occurred while signing in.',
      registerTitle: 'Create Your Wallet',
      registerSubtitle: 'Set up a virtual wallet and start tracking your expenses.',
      username: 'Username',
      usernamePlaceholder: 'Username',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Confirm password',
      registering: 'Registering...',
      createAccount: 'Sign Up',
      hasAccount: 'Already have an account?',
      signInLink: 'Sign in',
      passwordMismatch: 'Passwords do not match',
      enterUsername: 'Please enter a username',
      registrationFailed: 'Registration failed',
      genericRegisterError: 'An error occurred while registering.',
      supabaseNotConfigured: 'Supabase chưa cấu hình',
      supabaseConfigText: 'Vui lòng thêm biến môi trường VITE_SUPABASE_URL và VITE_SUPABASE_ANON_KEY để đăng nhập.',
      supabaseRegisterText: 'Vui lòng thêm biến môi trường VITE_SUPABASE_URL và VITE_SUPABASE_ANON_KEY để đăng ký người dùng.',
    },
  },
  vi: {
    language: 'Ngôn ngữ',
    english: 'English',
    vietnamese: 'Tiếng Việt',
    nav: {
      home: 'Trang chủ',
      transactions: 'Giao dịch',
      categories: 'Phân loại',
      statistics: 'Thống kê',
      settings: 'Cài đặt',
    },
    header: {
      title: 'Quản lý chi tiêu',
      subtitle: 'Theo dõi chi tiêu nhanh, gọn và hiện đại cho doanh nghiệp của bạn.',
    },
    home: {
      loading: 'Đang tải dashboard...',
      welcomeTitle: 'Chào mừng bạn đến với Finance Studio',
      welcomeText: 'Theo dõi chi tiêu, phân loại chi phí và khám phá dashboard ngay cả trước khi đăng nhập.',
      gettingStarted: 'Bắt đầu',
      step1: 'Thêm danh mục và quản lý ngân sách',
      step2: 'Ghi nhận thu nhập và chi tiêu chỉ trong vài giây',
      step3: 'Xem biểu đồ hiệu suất và xu hướng',
      overview: 'Tổng quan dashboard',
      overviewTitle: 'Quản lý tiền bạc rõ ràng hơn',
      overviewText: 'Một công cụ theo dõi chi tiêu hiện đại với thông tin nhanh, kiểm soát danh mục thông minh và phân tích xu hướng tài chính.',
      wallet: 'Ví',
      expenses: 'Chi tiêu',
      walletBalance: 'Số dư ví',
      latestInsights: 'Thông tin mới nhất',
      latestInsightsText: 'Một cái nhìn nhanh về danh mục chi tiêu và dòng tiền của bạn.',
      topCategory: 'Danh mục hàng đầu',
      noCategories: 'Chưa có danh mục nào',
      transactionCount: 'Số giao dịch',
      expenseVsIncome: 'Chi tiêu so với thu nhập',
      expenseByCategory: 'Chi tiêu theo danh mục',
      monthlyTrend: 'Xu hướng theo tháng',
      basedOn: 'Dựa trên các giao dịch đã ghi nhận',
      income: 'Thu nhập',
      expensesChart: 'Chi tiêu',
      noData: 'Chưa có dữ liệu',
    },
    transaction: {
      loading: 'Đang tải...',
      requiredLoginTitle: 'Yêu cầu đăng nhập',
      requiredLoginText: 'Vui lòng đăng nhập để quản lý giao dịch của bạn.',
      title: 'Giao dịch',
      subtitle: 'Quản lý giao dịch',
      records: 'bản ghi được tìm thấy',
      addNew: 'Thêm giao dịch mới',
      description: 'Mô tả',
      amount: 'Số tiền',
      chooseCategory: 'Chọn danh mục',
      note: 'Ghi chú (tùy chọn)',
      addButton: 'Thêm giao dịch',
      viewDetails: 'Xem chi tiết',
      hideDetails: 'Ẩn chi tiết',
      delete: 'Xóa',
      noteLabel: 'Ghi chú',
      noNote: 'Không có ghi chú bổ sung.',
      completeFields: 'Vui lòng điền đầy đủ thông tin giao dịch.',
      fallbackLocal: 'Giao dịch đã được lưu cục bộ vì Supabase không khả dụng.',
      failedAdd: 'Thêm giao dịch thất bại.',
      failedDelete: 'Xóa giao dịch thất bại.',
      confirmDelete: 'Bạn có chắc muốn xóa giao dịch này không?',
      loadCategoriesError: 'Không thể tải danh mục.',
      loadTransactionsError: 'Không thể tải giao dịch.',
      unknown: 'Không xác định',
      noCategories: 'Chưa có danh mục nào',
      date: 'Ngày',
    },
    categories: {
      title: 'Quản lý danh mục',
      subtitle: 'Tạo, chỉnh sửa và tổ chức các danh mục thu nhập và chi tiêu của bạn.',
      loading: 'Đang tải danh mục...',
      addTitle: 'Thêm danh mục',
      nameLabel: 'Tên danh mục',
      namePlaceholder: 'Nhập tên danh mục',
      typeLabel: 'Loại danh mục',
      expense: 'Chi tiêu',
      income: 'Thu nhập',
      addButton: 'Thêm danh mục',
      yourCategories: 'Danh mục của bạn',
      items: 'mục',
      noCategories: 'Chưa có danh mục nào. Hãy bắt đầu bằng cách thêm một danh mục.',
      save: 'Lưu',
      cancel: 'Hủy',
      edit: 'Sửa',
      delete: 'Xóa',
      loginRequiredTitle: 'Yêu cầu đăng nhập',
      loginRequiredText: 'Vui lòng đăng nhập để xem và quản lý danh mục của bạn.',
      supabaseNotConfigured: 'Supabase chưa được cấu hình',
      supabaseConfigText: 'Vui lòng thêm VITE_SUPABASE_URL và VITE_SUPABASE_ANON_KEY để quản lý danh mục.',
      errorName: 'Vui lòng nhập tên danh mục',
      loginFirst: 'Vui lòng đăng nhập trước khi thêm danh mục.',
      fallbackLocal: 'Danh mục đã được lưu cục bộ vì Supabase không khả dụng.',
      deleteLogin: 'Vui lòng đăng nhập trước.',
      emptyName: 'Tên danh mục không được để trống!',
      updateError: 'Lỗi khi cập nhật danh mục.',
      addError: 'Lỗi khi thêm danh mục.',
      deleteError: 'Lỗi khi xóa danh mục.',
      loadError: 'Không thể tải danh mục.',
      missingTable: 'Không tìm thấy bảng danh mục. Đang sử dụng dữ liệu cục bộ.',
    },
    statistics: {
      loading: 'Đang tải thống kê...',
      title: 'Thống kê',
      subtitle: 'Theo dõi nơi tiền của bạn được chi tiêu mỗi tháng.',
      supabaseConfigText: 'Supabase chưa được cấu hình. Vui lòng thêm VITE_SUPABASE_URL và VITE_SUPABASE_ANON_KEY.',
      signInText: 'Đăng nhập để xem phân tích chi tiêu cá nhân hóa.',
      totalIncome: 'Tổng thu nhập',
      totalExpenses: 'Tổng chi tiêu',
      balance: 'Số dư',
      monthlyTitle: 'Phân tích chi tiêu theo tháng',
      quarterlyTitle: 'Thu nhập và chi tiêu theo quý',
      categoryTitle: 'Phân tích chi tiêu theo danh mục',
    },
    settings: {
      account: 'Tài khoản',
      title: 'Cài đặt hồ sơ',
      subtitle: 'Quản lý tài khoản, tùy chọn và ví của bạn.',
      loading: 'Đang tải thông tin hồ sơ...',
      pleaseLogin: 'Vui lòng đăng nhập',
      loginText: 'Không tìm thấy thông tin người dùng. Vui lòng đăng nhập lại để tiếp tục.',
      goToLogin: 'Đi đến đăng nhập',
      supabaseNotConfigured: 'Supabase chưa được cấu hình',
      supabaseConfigText: 'Vui lòng thêm biến môi trường VITE_SUPABASE_URL và VITE_SUPABASE_ANON_KEY để tải thông tin hồ sơ.',
      walletBalance: 'Số dư ví',
      updatePhoto: 'Nhấn vào biểu tượng máy ảnh để cập nhật ảnh hồ sơ.',
      personalInfo: 'Thông tin cá nhân',
      personalInfoText: 'Cập nhật thông tin hồ sơ cơ bản của bạn.',
      username: 'Tên người dùng',
      emailAddress: 'Địa chỉ email',
      emailHint: 'Địa chỉ email không thể thay đổi ở đây.',
      currency: 'Tiền tệ',
      passwordSecurity: 'Mật khẩu & bảo mật',
      passwordSecurityText: 'Giữ tài khoản của bạn an toàn với mật khẩu mạnh.',
      currentPassword: 'Mật khẩu hiện tại',
      newPassword: 'Mật khẩu mới',
      passwordHint: 'Chỉ cần thiết khi thay đổi mật khẩu.',
      newPasswordHint: 'Để trống nếu bạn không muốn thay đổi.',
      wallet: 'Ví',
      walletText: 'Quản lý số dư ví hiện tại của bạn.',
      currentWalletBalance: 'Số dư ví hiện tại',
      amount: 'Số tiền',
      action: 'Hành động',
      addAmount: 'Thêm số tiền',
      setNewValue: 'Đặt giá trị mới',
      addDesc: 'cộng số tiền đã nhập vào số dư hiện tại.',
      setDesc: 'thay thế số dư hiện tại.',
      logout: 'Đăng xuất',
      saveChanges: 'Lưu thay đổi',
      saving: 'Đang lưu...',
      usernamePlaceholder: 'Nhập tên người dùng',
      emailPlaceholder: 'Nhập email',
      amountPlaceholder: 'Nhập số tiền, ví dụ 1.000',
      accountMessage: 'Người dùng',
      enterCurrentPassword: 'Nhập mật khẩu hiện tại',
      enterNewPassword: 'Nhập mật khẩu mới',
      usernameRequired: 'Tên người dùng không được để trống.',
      passwordRequired: 'Vui lòng nhập mật khẩu cũ để cập nhật mật khẩu mới.',
      oldPasswordIncorrect: 'Mật khẩu cũ không chính xác.',
      invalidBalance: 'Vui lòng nhập số dư hợp lệ và không âm.',
      saveSuccess: 'Cài đặt đã được lưu thành công!',
      saveError: 'Không thể lưu cài đặt. Vui lòng thử lại.',
      profileText: 'Quản lý tài khoản, tùy chọn và ví của bạn.',
      currentBalanceLabel: 'Số dư ví hiện tại',
    },
    auth: {
      loginTitle: 'Đăng nhập ví',
      loginSubtitle: 'Đăng nhập để truy cập ví ảo và báo cáo chi tiêu.',
      email: 'Email',
      password: 'Mật khẩu',
      emailPlaceholder: 'Địa chỉ email',
      passwordPlaceholder: 'Mật khẩu',
      signingIn: 'Đang đăng nhập...',
      signIn: 'Đăng nhập',
      noAccount: 'Chưa có tài khoản?',
      signUp: 'Đăng ký',
      forgotPassword: 'Quên mật khẩu?',
      forgotPasswordTitle: 'Lấy lại mật khẩu',
      forgotPasswordText: 'Nhập email và chúng tôi sẽ gửi cho bạn liên kết đặt lại mật khẩu.',
      sendResetLink: 'Gửi liên kết đặt lại',
      resetLinkSent: 'Vui lòng kiểm tra email để nhận liên kết đặt lại mật khẩu.',
      resetLinkError: 'Không thể gửi liên kết đặt lại. Vui lòng thử lại.',
      backToLogin: 'Quay lại đăng nhập',
      resetPasswordTitle: 'Đặt mật khẩu mới',
      newPassword: 'Mật khẩu mới',
      confirmNewPassword: 'Xác nhận mật khẩu mới',
      passwordUpdated: 'Mật khẩu đã được cập nhật. Bạn có thể đăng nhập ngay bây giờ.',
      passwordUpdateError: 'Không thể cập nhật mật khẩu. Vui lòng thử lại.',
      passwordsDoNotMatch: 'Mật khẩu không khớp.',
      invalidCredentials: 'Email hoặc mật khẩu không hợp lệ',
      confirmEmail: 'Vui lòng xác nhận email hoặc kiểm tra thông tin đăng nhập.',
      genericError: 'Đã xảy ra lỗi khi đăng nhập.',
      registerTitle: 'Tạo ví của bạn',
      registerSubtitle: 'Thiết lập ví ảo và bắt đầu theo dõi chi tiêu.',
      username: 'Tên người dùng',
      usernamePlaceholder: 'Tên người dùng',
      confirmPassword: 'Xác nhận mật khẩu',
      confirmPasswordPlaceholder: 'Xác nhận mật khẩu',
      registering: 'Đang đăng ký...',
      createAccount: 'Đăng ký',
      hasAccount: 'Đã có tài khoản?',
      signInLink: 'Đăng nhập',
      passwordMismatch: 'Mật khẩu không khớp',
      enterUsername: 'Vui lòng nhập tên người dùng',
      registrationFailed: 'Đăng ký thất bại',
      genericRegisterError: 'Đã xảy ra lỗi khi đăng ký.',
      supabaseNotConfigured: 'Supabase chưa cấu hình',
      supabaseConfigText: 'Vui lòng thêm biến môi trường VITE_SUPABASE_URL và VITE_SUPABASE_ANON_KEY để đăng nhập.',
      supabaseRegisterText: 'Vui lòng thêm biến môi trường VITE_SUPABASE_URL và VITE_SUPABASE_ANON_KEY để đăng ký người dùng.',
    },
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    try {
      return localStorage.getItem('language') || 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('language', language);
    } catch {
      //no comment
    }
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: translations[language] || translations.en,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
